### ISSUE TITLE
使用自助分析，报 ModuleNotFoundError: No module named 'segment.analytics'  

### ISSUE THREAD

**Issue by hope1234567hope** [wrss01/snb-docker-compose#1]
使用自助分析，报如下的错误
-------------------------------------ModuleNotFoundError                       Traceback (most recent call last)Cell In [45], line 1
----> 1 from snb_plugin.snbcharts import snb_walker
      2 walker = snb_walker.walk(dataset=df, i18nLang='zh-CN', dark='media', theme_key='vega',use_duckdb=0)
File </root/.pyenv/versions/3.9.19/envs/user_env/lib/python3.9/site-packages/snb_plugin/snbcharts/snb_walker.py>:1
File <frozen snb_plugin.snbcharts.snb_walker>:17
File </root/.pyenv/versions/3.9.19/envs/user_env/lib/python3.9/site-packages/pygwalker/api/pygwalker.py>:1
File <frozen pygwalker.api.pygwalker>:41
File </root/.pyenv/versions/3.9.19/envs/user_env/lib/python3.9/site-packages/pygwalker/services/track.py>:1
File <frozen pygwalker.services.track>:7
ModuleNotFoundError: No module named 'segment.analytics'  请问怎么解决？

**Comment by wrss01** [comment]
抱歉，两个依赖包忘记打入镜像了，可以再notebook 里面分别安装：
pip install segment-analytics-python==2.2.3
pip install kanaries_track==0.0.4
![image](https://github.com/wrss01/snb-docker-compose/assets/39665821/4b1ed6cb-a287-49db-8007-8644e09a63de)

安装成功后，工期kernel，菜单Kernel --> 重启Kernel。
